services:
  fsl:
    image: idossha/ti-csc_fsl:v1.3.0
    container_name: fsl_container
    volumes:
      - fsl_volume:/usr/local/fsl/
    networks:
      - ti_network

  freesurfer:
    image: idossha/ti-csc_freesurfer:v1.3.0
    container_name: freesurfer_container
    volumes:
      - freesurfer_volume:/usr/local/freesurfer/
    networks:
      - ti_network

  simnibs:
    # image: idossha/ti-csc_simnibs:v1.3.1
    image: idossha/simnibs:4.5.0
    container_name: simnibs_container
    environment:
      - USER=root
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
      - FSLDIR=/usr/local/fsl
      - FSLOUTPUTTYPE=NIFTI_GZ
      - FSLMULTIFILEQUIT=TRUE
      - POSSUMDIR=/usr/local/fsl
      - FREESURFER_HOME=/usr/local/freesurfer
      - SUBJECTS_DIR=/usr/local/freesurfer/subjects
      - FS_LICENSE=/usr/local/freesurfer/license.txt
      - LOCAL_PROJECT_DIR=${LOCAL_PROJECT_DIR}
      - PROJECT_DIR_NAME=${PROJECT_DIR_NAME}
    volumes:
      - fsl_volume:/usr/local/fsl/
      - freesurfer_volume:/usr/local/freesurfer/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${LOCAL_PROJECT_DIR}:/mnt/${PROJECT_DIR_NAME}
      - ${PROJECT_ROOT}:/ti-csc-2.0
    networks:
      - ti_network
    depends_on:
      - fsl
      - freesurfer
    tty: true
    stdin_open: true
    working_dir: /ti-csc
    command: ["/bin/bash"]

networks:
  ti_network:
    driver: bridge

volumes:
  fsl_volume:
  freesurfer_volume:

