# Temporal Interference Toolbox GitHub Pages Configuration
title: Temporal Interference Toolbox
author: Ido Haber
email: ihaber@wisc.edu
baseurl: "/TI-Toolbox" # Your repository name
url: "https://idossha.github.io" # Your GitHub Pages URL

# Theme and plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
header_pages:
  - wiki/wiki.md
  - releases/releases.md
  - about/about.md
  - installation.md

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md 
